ope/config/routes.rb
Rails.application.routes.draw do
  resources :fornecedors
  resources :pedido_prdoutos
  resources :pedidos
  resources :clientes
  resources :produtos
  resources :atendentes
  root 'page#index'
  get 'page/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ope/app/models/pedido_prdouto.rb
class PedidoPrdouto < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
end

ope/app/controllers/pedido_prdoutos_controller.rb
class PedidoPrdoutosController < ApplicationController
  before_action :set_pedido_prdouto, only: [:show, :edit, :update, :destroy]

  # GET /pedido_prdoutos
  # GET /pedido_prdoutos.json
  def index
    @pedido_prdoutos = PedidoPrdouto.all
  end

  # GET /pedido_prdoutos/1
  # GET /pedido_prdoutos/1.json
  def show
  end

  # GET /pedido_prdoutos/new
  def new
    @pedido_prdouto = PedidoPrdouto.new
  end

  # GET /pedido_prdoutos/1/edit
  def edit
  end

  # POST /pedido_prdoutos
  # POST /pedido_prdoutos.json
  def create
    @pedido_prdouto = PedidoPrdouto.new(pedido_prdouto_params)

    respond_to do |format|
      if @pedido_prdouto.save
        format.html { redirect_to @pedido_prdouto, notice: 'Pedido prdouto was successfully created.' }
        format.json { render :show, status: :created, location: @pedido_prdouto }
      else
        format.html { render :new }
        format.json { render json: @pedido_prdouto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedido_prdoutos/1
  # PATCH/PUT /pedido_prdoutos/1.json
  def update
    respond_to do |format|
      if @pedido_prdouto.update(pedido_prdouto_params)
        format.html { redirect_to @pedido_prdouto, notice: 'Pedido prdouto was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido_prdouto }
      else
        format.html { render :edit }
        format.json { render json: @pedido_prdouto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedido_prdoutos/1
  # DELETE /pedido_prdoutos/1.json
  def destroy
    @pedido_prdouto.destroy
    respond_to do |format|
      format.html { redirect_to pedido_prdoutos_url, notice: 'Pedido prdouto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido_prdouto
      @pedido_prdouto = PedidoPrdouto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_prdouto_params
      params.require(:pedido_prdouto).permit(:pedido_id, :produto_id)
    end
end

ope/app/helpers/pedido_prdoutos_helper.rb
module PedidoPrdoutosHelper
end

ope/app/views/pedido_prdoutos/_form.html.erb
<%= form_with(model: pedido_prdouto, local: true) do |form| %>
  <% if pedido_prdouto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido_prdouto.errors.count, "error") %> prohibited this pedido_prdouto from being saved:</h2>

      <ul>
        <% pedido_prdouto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pedido_id %>
    <%= form.text_field :pedido_id %>
  </div>

  <div class="field">
    <%= form.label :produto_id %>
    <%= form.text_field :produto_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ope/app/views/pedido_prdoutos/edit.html.erb
<h1>Editing Pedido Prdouto</h1>

<%= render 'form', pedido_prdouto: @pedido_prdouto %>

<%= link_to 'Show', @pedido_prdouto %> |
<%= link_to 'Back', pedido_prdoutos_path %>

ope/app/views/pedido_prdoutos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedido Prdoutos</h1>

<table>
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedido_prdoutos.each do |pedido_prdouto| %>
      <tr>
        <td><%= pedido_prdouto.pedido_id %></td>
        <td><%= pedido_prdouto.produto_id %></td>
        <td><%= link_to 'Show', pedido_prdouto %></td>
        <td><%= link_to 'Edit', edit_pedido_prdouto_path(pedido_prdouto) %></td>
        <td><%= link_to 'Destroy', pedido_prdouto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido Prdouto', new_pedido_prdouto_path %>

ope/app/views/pedido_prdoutos/new.html.erb
<h1>New Pedido Prdouto</h1>

<%= render 'form', pedido_prdouto: @pedido_prdouto %>

<%= link_to 'Back', pedido_prdoutos_path %>

ope/app/views/pedido_prdoutos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @pedido_prdouto.pedido_id %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @pedido_prdouto.produto_id %>
</p>

<%= link_to 'Edit', edit_pedido_prdouto_path(@pedido_prdouto) %> |
<%= link_to 'Back', pedido_prdoutos_path %>