ope/config/routes.rb
Rails.application.routes.draw do
  resources :fornecedors
  resources :pedido_prdoutos
  resources :pedidos
  resources :clientes
  resources :produtos
  resources :atendentes
  root 'page#index'
  get 'page/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ope/app/models/produto.rb
class Produto < ApplicationRecord
end

ope/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:descricao, :marca, :cor, :preco)
    end
end

ope/app/helpers/produtos_helper.rb
module ProdutosHelper
end

ope/app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">

                            <%= form.label :descricao %>
                            <%= form.text_field :descricao ,class:'form-control'%>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :marca %>
                            <%= form.text_field :marca,class:'form-control' %>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :cor %>
                            <%= form.color_field :cor ,class:'form-control'%>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :preco %>
                            <%= form.number_field :preco ,class:'form-control'%>
                          </div>
                        </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

ope/app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Mostrar', @produto ,class:'btn btn-info'%> |
<%= link_to 'Voltar', produtos_path,class:'btn btn-danger'%>

ope/app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>
<div class="col-md-12">
              <div class="card">

                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
<thead class=" text-primary">
    <tr>
      <th>Descricao</th>
      <th>Marca</th>
      <th>Cor</th>
      <th>Preco</th>
      <th colspan="3">Acoes</th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.descricao %></td>
        <td><%= produto.marca %></td>
        <td style='background:<%= produto.cor %>'></td>
        <td><%= produto.preco %></td>
        <td><%= link_to 'Mostrar', produto ,class: 'btn btn-primary' %>
      <%= link_to 'Editar', edit_produto_path(produto),class: 'btn btn-warning' %>
        <%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Voce tem certeza em deletar o produto' << produto.descricao << '?' },class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>

<br>

<%= link_to 'Novo Produto', new_produto_path, class: 'btn btn-primary' %>

ope/app/views/produtos/new.html.erb
<h1 class="col-md-12 text-center">Novo Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Voltar', produtos_path,class: 'btn btn-danger'%>

ope/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-12">
<div class="row">
  <div class="col-md-12">
                <h1 class="only-bottom-margin"><%= @produto.descricao%></h1>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <span class="text-muted">Marca:</span> <%=@produto.marca %><br>
                <span class="text-muted">Cor</span> <span style = 'background:<%= @produto.cor  %> '><%= @produto.cor  %></span><br>
                <span class="text-muted">Preco</span> <%= @produto.preco %> %><br>
                <small class="text-muted">Cadastramento: <%=@produto.created_at %></small>
              </div>
</div>
</div>

<%= link_to 'Editar', edit_produto_path(@produto),class: 'btn btn-warning' %> |
<%= link_to 'Voltar', produtos_path,class:'btn btn-danger' %>