ope/config/routes.rb
Rails.application.routes.draw do
  resources :fornecedors
  resources :pedido_prdoutos
  resources :pedidos
  resources :clientes
  resources :produtos
  resources :atendentes
  root 'page#index'
  get 'page/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ope/app/models/atendente.rb
class Atendente < ApplicationRecord
end

ope/app/controllers/atendentes_controller.rb
class AtendentesController < ApplicationController
  before_action :set_atendente, only: [:show, :edit, :update, :destroy]

  # GET /atendentes
  # GET /atendentes.json
  def index
    @atendentes = Atendente.all
  end

  # GET /atendentes/1
  # GET /atendentes/1.json
  def show
  end

  # GET /atendentes/new
  def new
    @atendente = Atendente.new
  end

  # GET /atendentes/1/edit
  def edit
  end

  # POST /atendentes
  # POST /atendentes.json
  def create
    @atendente = Atendente.new(atendente_params)

    respond_to do |format|
      if @atendente.save
        format.html { redirect_to @atendente, notice: 'Atendente was successfully created.' }
        format.json { render :show, status: :created, location: @atendente }
      else
        format.html { render :new }
        format.json { render json: @atendente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atendentes/1
  # PATCH/PUT /atendentes/1.json
  def update
    respond_to do |format|
      if @atendente.update(atendente_params)
        format.html { redirect_to @atendente, notice: 'Atendente was successfully updated.' }
        format.json { render :show, status: :ok, location: @atendente }
      else
        format.html { render :edit }
        format.json { render json: @atendente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atendentes/1
  # DELETE /atendentes/1.json
  def destroy
    @atendente.destroy
    respond_to do |format|
      format.html { redirect_to atendentes_url, notice: 'Atendente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atendente
      @atendente = Atendente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atendente_params
      params.require(:atendente).permit(:nome, :email, :senha)
    end
end

ope/app/helpers/atendentes_helper.rb
module AtendentesHelper
end

ope/app/views/atendentes/_form.html.erb
<%= form_with(model: atendente, local: true) do |form| %>
  <% if atendente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atendente.errors.count, "error") %> prohibited this atendente from being saved:</h2>

      <ul>
        <% atendente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">

                            <%= form.label :nome %>
                            <%= form.text_field :nome,class:'form-control'%>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :email %>
                            <%= form.text_field :email,class:'form-control' %>
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group bmd-form-group">
                            <%= form.label :senha %>
                            <%= form.password_field :senha ,class:'form-control'%>
                          </div>
                        </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

ope/app/views/atendentes/edit.html.erb
mostrar<h1>Editing Atendente</h1>

<%= render 'form', atendente: @atendente %>

<%= link_to 'mostrar', @atendente, class:'btn btn-info'%> 
<%= link_to 'Voltar', atendentes_path ,class:'btn btn-danger'%>

ope/app/views/atendentes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atendentes</h1>
<div class="col-md-12">
              <div class="card">

                <div class="card-body">
                  <div class="table-responsive">
<table class="table">
  <thead class=" text-primary">
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th colspan="3">Acoes</th>
    </tr>
  </thead>

  <tbody>
    <% @atendentes.each do |atendente| %>
      <tr>
        <td><%= atendente.nome %></td>
        <td><%= atendente.email %></td>
        <td><%= atendente.senha %></td>
        <td><%= link_to 'Mostrar', atendente ,class: 'btn btn-primary'%></td>
        <td><%= link_to 'Editar', edit_atendente_path(atendente),class: 'btn btn-warning' %></td>
        <td><%= link_to 'Excluir', atendente, method: :delete, data: { confirm: 'Tem certeza em deletar o atendente '<< atendente.nome << ' ?' },class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>




<%= link_to 'Novo Atendente', new_atendente_path, class: 'btn btn-primary' %>

ope/app/views/atendentes/new.html.erb
<h1 class="col-md-12 text-center">Novo Atendente</h1>

<%= render 'form', atendente: @atendente %>

<%= link_to 'Voltar', atendentes_path, class:'btn btn-danger' %>

ope/app/views/atendentes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
<div class="row">
  <div class="col-md-12">
                <h1 class="only-bottom-margin">  <%= @atendente.nome %></h1>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <span class="text-muted">Email:</span>  <%= @atendente.email %><br>
                <span class="text-muted">Senha</span> <%= @atendente.senha %><br>
                <small class="text-muted">Admissao: <%=@atendente.created_at %></small>
              </div>
</div>

<%= link_to 'Editar', edit_atendente_path(@atendente),class: 'btn btn-warning'%>
<%= link_to 'Voltar', atendentes_path,class:'btn btn-danger' %>