ope/config/routes.rb
Rails.application.routes.draw do
  resources :fornecedors
  resources :pedido_prdoutos
  resources :pedidos
  resources :clientes
  resources :produtos
  resources :atendentes
  root 'page#index'
  get 'page/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ope/app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
  has_many  :produto_fornecedor,dependent: :delete_all
  has_many :produtos , through: :produto_fornecedor,dependent: :delete_all
end

ope/app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  before_action :set_fornecedor, only: [:show, :edit, :update, :destroy]

  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1
  # PATCH/PUT /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: 'Fornecedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :email, :telefone, :cpf,:produto_ids => [])
    end
end

ope/app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

ope/app/views/fornecedors/_form.html.erb
<%= form_with(model: fornecedor, local: true) do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
        <% fornecedor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :nome %>
                            <%= form.text_field :nome ,class:'form-control'%>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :email %>
                            <%= form.email_field :email ,class:'form-control'%>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :telefone %>
                              <%= form.telephone_field :telefone,class:'form-control' %>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <%= form.label :cpf %>
                            <%= form.text_field :cpf,class:'form-control' %>
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group bmd-form-group">
                            <%= form.label :produto %>
                            <%= collection_select(:fornecedor,:produto_ids,Produto.all,:id,:descricao,{} ,{class:'browser-default custom-select',:multiple  => true}) %>
                          </div>
                        </div>

  </div>




  <div class="d-flex justify-content-center">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

ope/app/views/fornecedors/edit.html.erb
<h1>Editing Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Mostrar', @fornecedor, class: 'btn btn-info' %> 
<%= link_to 'Voltar', fornecedors_path, class: 'btn btn-danger' %>

ope/app/views/fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fornecedores</h1>
<div class="col-md-12">
              <div class="card">

                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Cpf</th>
      <th>Produtos</th>
      <th colspan="3">Acoes</th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nome %></td>
        <td><%= fornecedor.email %></td>
        <td><%= fornecedor.telefone %></td>
        <td><%= fornecedor.cpf %></td>
        <td>
          <% fornecedor.produtos.each do |produto|  %>
          <%= produto.descricao %>
          <% end %>
        </td>
        <td><%= link_to 'Mostrar', fornecedor ,class: 'btn btn-primary'%>
        <%= link_to 'Editar', edit_fornecedor_path(fornecedor),class: 'btn btn-warning' %>
        <%= link_to 'Excluir', fornecedor, method: :delete, data: { confirm: 'Voce tem certeza em excluir o fornecedor ' << fornecedor.nome << ' ?' },class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Fornecedor', new_fornecedor_path,class: 'btn btn-primary' %>

ope/app/views/fornecedors/new.html.erb
<h1 class="col-md-12 text-center">Novo Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Voltar', fornecedors_path,class: 'btn btn-danger' %>

ope/app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
<div class="row">
  <div class="col-md-12">
                <h1 class="only-bottom-margin"><%= @fornecedor.nome %></h1>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <span class="text-muted">Email:</span> <%=@fornecedor.email %><br>
                <span class="text-muted">Cpf</span> <%= @fornecedor.cpf %><br>
                <span class="text-muted">Telefone</span> <%=@fornecedor.telefone %><br>
                <span class="text-muted">Produtos</span> <span><% @fornecedor.produtos.each do |prod| %><%= prod.descricao %> <% end%></span><br>
                <small class="text-muted">Criacao: <%=@fornecedor.created_at %></small>
              </div>
</div>
</div>
<%= link_to 'Editar', edit_fornecedor_path(@fornecedor) , class: 'btn btn-warning' %> |
<%= link_to 'Voltar', fornecedors_path, class: ' btn btn-danger' %>